name: mhkit_docs2
dependencies:
  - python >=3.9,<3.12
  - pip
  - mhkit
  - pandoc
  - pip:
    - sphinx
    - sphinxcontrib-bibtex
    - sphinxcontrib-matlabdomain
    - sphinx_rtd_theme
    - nbsphinx
    - sphinxcontrib-googleanalytics
    - ipython
